name: baykar
channels:
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - notebook
  - joblib
  - xgboost
  - streamlit
  - pip

  # Pip-installed extras
  - pip:
      - tensorflow
      - plotly

